### ISSUE TITLE
WhatsApp is broken... 

### ISSUE THREAD

**Issue by baterax** [ducfilan/Dark-mode-Franz-Ferdi#25]
Hi!
I noticed that the WhatsApp dark mode started behaving strangely since a couple days ago (some green colors back, blue tick marks not showing), so I tried to reinstall it and now it doesn't work at all.
Steps taken:
- Remove the service
- delete whatsapp folder from Appdata/recipes folder
- Re-add WhatsApp as a service
- Completely close Franz
- Download dark mode CSS file
- Save it in recipes/whatsapp
- Reopen Franz

The WhatsApp service now has the "Dark Mode" toggle button, as normal, but it doesn't do anything.
HELP!

**Comment by yannickdemets** [comment]
Hi,
Just to confirm that I have the same issues. Some normal colours are back, meaning the white at the search bar and the down arrow at the discussions are back to green when clicking on them. I tried the same steps to try to solve the problem but still have the issues as before (did not got worse).

thanks for the help in advance

**Comment by ducfilan** [comment]
I updated the new version. Check it out.
