### ISSUE TITLE
dark conversation text

### ISSUE THREAD

**Issue by gle2n** [ducfilan/Dark-mode-Franz-Ferdi#27]
the text of the conversation became dark in WhatsApp. With a dark background, it's unreadable. I managed to "fix" it by adding:

.copyable-text{
  color: #eee;
}

at the end of the css file.

(Windows 10, Franz 5.4.0)

**Comment by lapentad** [comment]
Thanks, works great again

**Comment by gle2n** [comment]
also had to add 

._3FRCZ{
	color: #eee !important;
}

for the colour of the text of the textinput when you write a message

**Comment by ducfilan** [comment]
Thank you @gle2n 
I added a new version with your suggestion.
You can also make a pull request in the future if you find other problems.
