### ISSUE TITLE
WhatsApp input message field is impossible to read

### ISSUE THREAD

**Issue by Zireael13** [ducfilan/Dark-mode-Franz-Ferdi#28]
Just updated to the latest WhatsApp darkmode.css, after the previous one had issues with the text in messages not being able to be read. Now this one has a different problem, where the input field is white (which it shouldn't be) and the text is light grey, making it very hard to read what you are writing.

**Comment by lapentad** [comment]
Go into %appdata%/Franz/recipes/whatsapp/darkmode.css 
At the bottom of the file change "_3FRCZ" reference color from #eee (light color) to #282d37 (dark color)
._3FRCZ{
color: #282d37 !important;
}

**Comment by ducfilan** [comment]
> Go into %appdata%/Franz/recipes/whatsapp/darkmode.css
> At the bottom of the file change "_3FRCZ" reference color from #eee (light color) to #282d37 (dark color)
> ._3FRCZ{
> color: #282d37 !important;
> }

Thank you. 
Can you make a pull request? @lapentad

**Comment by Zireael13** [comment]
Updated to the new file, and confirmed the change from @lapentad was in there. However, this change just makes the text darker so it is easier to read, and does not fix the color of the box, which is white and does not match the rest of the dark theme. I've edited the code myself and the change that should be added is:

._3FRCZ{
  color: #eee !important;
}

._3uMse{
  background-color: #282d37 !important;
  border-color: #282d37 !important;
}
