### ISSUE TITLE
Update Messenger CSS to match official app's dark mode

### ISSUE THREAD

**Issue by itmestan** [ducfilan/Dark-mode-Franz-Ferdi#35]
love the dark mode option, thx a ton!

the official Win10 FB Messenger app has a really nice dark mode itself and I was wondering if it'd be possible to update the CSS to match it. I tried myself and because I'm still new to CSS, I didn't work out. :\

mostly what I'm hoping for is to match the colors of the Win10 Messenger app's left-hand contact bar (background color, scroll bar color, etc). that's it.

many thanks again, crossing my fingers for an update!

**Comment by baterax** [comment]
I second this!
