### ISSUE TITLE
Messenger stoped working

### ISSUE THREAD

**Issue by nekajcasa** [ducfilan/Dark-mode-Franz-Ferdi#44]
Dark mode in Facebook Messenger, is not working anymore... Only search bar is dark.

![image](https://user-images.githubusercontent.com/25286278/102222369-a0ba6300-3ee3-11eb-9944-8cfde1520226.png)

**Comment by kacboy** [comment]
Same, happens on Big Sur and Windows 10 for me.

**Comment by ducfilan** [comment]
Fixed in the new version. Please check.

**Comment by Julian88Tex** [comment]
Is occuring again #45
