### ISSUE TITLE
Bug: Facebook 

### ISSUE THREAD

**Issue by Julian88Tex** [ducfilan/Dark-mode-Franz-Ferdi#45]
Facebook Dark Mode is no longer working. The Login screen is dark, but on the messages screen only the search messenger field is dark.

Found on Ferdi  5.5.0

May have been fixed once before: #44 

<img width="991" alt="Screen Shot 2020-12-21 at 11 42 58 AM" src="https://user-images.githubusercontent.com/459099/102815918-07c39600-4382-11eb-9a91-164e9dfcdab3.png">

![Screen Shot 2020-12-21 at 11 44 12 AM](https://user-images.githubusercontent.com/459099/102815855-ecf12180-4381-11eb-8fc1-f034ed69446e.png)

**Comment by madsmtm** [comment]
Duplicate of #44, this is already fixed!

**Comment by Julian88Tex** [comment]
@madsmtm Thanks for the link, unfortunately, it seems to have to be happening again. I've completed the readme steps including toggling dark mode and reloading Ferdi/service with no luck. This is occurring on Ferdi 5.5.0 by the way.

**Comment by dhoangnghia-mdsol** [comment]
Did you try the newest version?

**Comment by Julian88Tex** [comment]
@madsmtm scratch that didn't see the commit from 14 hours ago. Working now thanks!
