### ISSUE TITLE
Messenger scrollbar in Dark mode

### ISSUE THREAD

**Issue by Esarve** [ducfilan/Dark-mode-Franz-Ferdi#48]
is there any way to disable the white scrollbars on messenger dark mode?
![image](https://user-images.githubusercontent.com/5249580/122872233-f881cd00-d351-11eb-8005-2327c6cae84c.png)

**Comment by bundyo** [comment]
Just added a PR for this (#49).

**Comment by ducfilan** [comment]
Merged! Thank you @bundyo !
@Esarve Please check the latest version.
