### ISSUE TITLE
Service Request: Add LinkedIn Darkmode

### ISSUE THREAD

**Issue by Julian88Tex** [ducfilan/Dark-mode-Franz-Ferdi#6]
Service Request: Add LinkedIn Darkmode

**Comment by ducfilan** [comment]
LinkedIn is now supported.

**Comment by Julian88Tex** [comment]
![Screenshot 2019-09-10 00 08 38](https://user-images.githubusercontent.com/459099/64591649-2b1a2b80-d35f-11e9-9e57-0a20bee28a4b.png)
![Screenshot 2019-09-10 00 07 56](https://user-images.githubusercontent.com/459099/64591650-2b1a2b80-d35f-11e9-8f2b-8248b994b5e9.png)

Thanks... hmmm doesn't seem to be working for me though.

**Comment by jandreaucodes** [comment]
Doesn't seem to work for me, either. Should this be reopened?

**Comment by Julian88Tex** [comment]
Thought I'd bump since it still is an issue and any workaround previously stated don't seem to work for me. Only one that works right now is constantly refreshing and ~5% of the time it will reload into dark mode. This has to be repeated every time Ferdi ends a session.

**Comment by Julian88Tex** [comment]
Just found one other workaround. Open Ferdi Settings -> Your Services -> LinkedIn -> Save service.

**Comment by Julian88Tex** [comment]
@ducfilan Hey just checking to see if you've had any luck with this. Looks like dark mode is "turning on" now in Ferdi but just needs to have some CSS styling changes for it to be implemented in a usable way.

<img width="1352" alt="Screen Shot 2022-01-22 at 5 24 10 PM" src="https://user-images.githubusercontent.com/459099/150661012-f80763ac-c51a-4aaf-88b3-571a80ba3549.png">

**Comment by Julian88Tex** [comment]
Closing since LinkedIn has dark mode now and I just got it... finally!

https://www.linkedin.com/help/linkedin/answer/a524473/switch-between-dark-and-light-mode?lang=en
